repos:
  -   repo: https://github.com/Cretezy/flutter-format-pre-commit
      rev: "master"
      hooks:
        -   id: flutter-format
  -   repo: https://github.com/dluksza/flutter-analyze-pre-commit
      rev: "master"
      hooks:
        -   id: flutter-analyze
  -   repo: https://github.com/Virtomize/flutter-test-pre-commit
      rev: "main"
      hooks:
        -   id: flutter-test